[package]
name = "kitsune_p2p"
version = "0.0.1"
description = "p2p / dht communication framework"
license = "Apache-2.0"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[dependencies]
derive_more = "0.99.7"
futures = "0.3"
ghost_actor = "0.1.0"
shrinkwraprs = "0.3.0"
thiserror = "1.0.18"
tokio = { version = "0.2", features = [ "full" ] }

[dev-dependencies]
assert_matches = "1.3"
