[package]
name = "sx_lib3h_protocol"
version = "0.0.1"
description = "holochain lib3h protocol"
license = "GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.22"
base64 = "0.10.1"
sx_types = { path = "../types"}
rmp-serde = "0.13.7"
serde = { version = "1.0.104", features = ["derive"] }
url = { version = "2.1.0", features = ["serde"] }
