[workspace]
members = [
  # "crates/admin",
  "crates/dna_util",
  "crates/fixt",
  "crates/fixt/test",
  "crates/hdk3",
  "crates/hdk3_derive",
  "crates/holo_hash",
  
  "crates/monolith",

  "crates/holochain_conductor_api",
  "crates/holochain_lmdb",
  "crates/holochain_p2p",
  "crates/holochain_keystore",
  "crates/holochain_state",
  "crates/holochain_types",
  "crates/holochain_zome_types",

  "crates/kitsune_p2p/kitsune_p2p",
  "crates/kitsune_p2p/transport_quic",
  "crates/kitsune_p2p/types",
  "crates/kitsune_p2p/proxy",
  
  "crates/test_utils/wasm",
  "crates/test_utils/wasm_common",
  # "crates/websocket",
]

exclude = [
  "pseudocode",
  "crates/holochain_nucleus",
]

# These are the default params for RELEASE target
# Setting these for all dependencies... we'll only debug our own code
[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[patch.crates-io]

rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
#lmdb-rkv = { path = "../../rust/lmdb-rs" }
# holochain_wasmer_guest = { path = "../holochain-wasmer/crates/guest" }
# ghost_actor = { path = "../ghost_actor/crates/ghost_actor" }
# ghost_actor = { git = "https://github.com/holochain/ghost_actor.git", branch = "add_observability" }
holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization.git", branch = "no-rmp-error" }
# lair_keystore_api = { git = "https://github.com/holochain/lair.git", branch = "bump_ga" }
# lair_keystore_client = { git = "https://github.com/holochain/lair.git", branch = "bump_ga" }
# lair_keystore_api = { path = "../lair/crates/lair_keystore_api" }
# lair_keystore_client = { path = "../lair/crates/lair_keystore_client" }
# observability = { path = "../../rust/observability" }
tokio_safe_block_on = { git = "https://github.com/neonphog/tokio_safe_block_on.git", branch = "fix_holochain_bug" }
