[workspace]

members = [
  "crates/crypto",
  "crates/dna_util",
  "crates/fixt",
  "crates/fixt/test",
  "crates/keystore",
  "crates/holochain",
  "crates/holo_hash",
  "crates/holo_hash_core",
  "crates/state",
  "crates/types",
  "crates/websocket",
  "crates/test_utils/wasm",
  "crates/test_utils/wasm_common",
]

exclude = [
  "pseudocode",
]

[patch.crates-io]

# holochain_serialized_bytes = { version = "=0.0.39", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
# holochain_wasmer_common = { version = "=0.0.30", git = "https://github.com/holochain/holochain-wasmer.git", branch = "unpinned" }
# holochain_wasmer_guest = { version = "=0.0.24", git = "https://github.com/holochain/holochain-wasmer.git", branch = "unpinned" }
# holochain_wasmer_host = { version = "=0.0.30", git = "https://github.com/holochain/holochain-wasmer.git", branch = "unpinned" }

rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
#rkv = { path = "../../rust/rkv" }
lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
#lmdb-rkv = { path = "../../rust/lmdb-rs" }
