[package]
name = "kitsune_p2p_types"
version = "0.0.1"
description = "types subcrate for kitsune-p2p"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[dependencies]
derive_more = "0.99.7"
futures = "0.3"
ghost_actor = "0.2.1"
thiserror = "1.0.18"
tokio = { version = "0.2", features = [ "full" ] }
url2 = "0.0.5"
