[package]
name = "test_wasm_imports"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_imports"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
lazy_static = "1.4.0"
serde = "=1.0.104"
hdk3 = { path = "../../../../hdk" }
