[package]
name = "test_wasm_migrate_agent_pass"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
[workspace]

[lib]
name = "test_wasm_migrate_agent_pass"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
holochain_serialized_bytes = "=0.0.39"
holochain_wasmer_guest = "=0.0.31"
holochain_zome_types = { version = "=0.0.1", path = "../../../zome_types" }
lazy_static = "1.4.0"
serde = "=1.0.104"
test_wasm_common = { version = "=0.0.1", path = "../../wasm_common" }
wee_alloc = "=0.4.5"

[patch.crates-io]
