[package]
name = "test_wasm_entry_defs"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
[workspace]

[lib]
name = "test_wasm_entry_defs"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
holochain_serialized_bytes = "=0.0.40"
holochain_wasmer_guest = "=0.0.37"
holochain_zome_types = { version = "=0.0.1", path = "../../../zome_types" }
serde = "=1.0.104"


[patch.crates-io]
holochain_serialized_bytes = { version = "=0.0.40", git = "https://github.com/holochain/holochain-serialization.git", branch = "most-stringent-rmp-config" }
holochain_wasmer_guest = { version = "=0.0.37", git = "https://github.com/holochain/holochain-wasmer.git", branch = "extra-error-info" }

