[package]
name = "sx_legacy"
version = "0.0.1"
description = "holochain core"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
parking_lot = "0.10.0"
toml = "0.5.0"
holochain_json_derive = { version = "0.0.23", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
holochain_json_api = { version = "0.0.23", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
holochain_metrics = { version = "0.0.42-alpha5" }
holochain_common = { version = "0.0.42-alpha5" }
lib3h = "0.0.31"
lib3h_sodium = "0.0.38"
boolinator = "2.4.0"
sx_types = { path = "../types"}
