[package]
name = "holochain_legacy"
version = "0.0.1"
description = "Holochain legacy types"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
serde = "1.0.104"
holochain_serialized_bytes = "=0.0.45"
