[package]
name = "pewpewpew"
version = "0.0.1"
description = "Runs lots of benches (pews, geddit?)"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain"
documentation = "https://github.com/Holo-host/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
actix = "0.9"
once_cell = "1"
serde = "1"

[workspace]
