[package]
name = "holochain_keystore"
version = "0.0.1"
description = "keystore for libsodium keypairs"
license = "Apache-2.0"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "nacl", "libsodium", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
ghost_actor = "0.1.0"
holo_hash = { version = "0.0.1", path = "../holo_hash" }
holochain_crypto = { version = "0.0.1", path = "../crypto" }
holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization", branch = "2020-06-06-serde-bytes" }
serde = { version = "1.0.104", features = [ "derive" ] }
serde_bytes = "0.11"
thiserror = "1"
tokio = { version = "0.2", features = [ "full" ] }
tracing = "0.1"
