[package]
name = "holochain_keystore"
version = "0.0.1"
description = "keystore for libsodium keypairs"
license = "Apache-2.0"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["holochain", "holo", "nacl", "libsodium", "cryptography"]
categories = ["cryptography"]
edition = "2018"

[dependencies]
holochain_serialized_bytes = "0.0.39"
holo_hash = { version = "0.0.1", path = "../holo_hash" }
ghost_actor = "0.1.0-alpha.8"
serde = { version = "1.0.104", features = ["derive"] }
serde_bytes = "0.11"
holochain_crypto = { version = "0.0.1", path = "../crypto" }
thiserror = "1"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
