[package]
name = "observability"
version = "0.1.0"
authors = ["freesig <tom.gowan@holo.host>"]
edition = "2018"

[features]
default = ["opentelemetry-on"]
opentelemetry-off = []
opentelemetry-on = ["opentelemetry", "tracing-opentelemetry", "holochain_serialized_bytes", "serde", "serde_bytes"]

[dependencies]
chrono = "0.4.6"
derive_more = "0.99.3"
inferno = "0.10.0"
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
thiserror = "1.0.10"
tracing = "=0.1.21"
tracing-core = "=0.1.17"
tracing-flame = "0.1.0"
tracing-serde = "=0.1.2"
tracing-subscriber = "=0.2.15"

opentelemetry = { version = "0.8", default-features = false, features = ["trace", "serialize"], optional = true }
tracing-opentelemetry = { version = "0.8.0", optional = true }
holochain_serialized_bytes = {version = "=0.0.45", optional = true }
serde = { version = "1", optional = true }
serde_bytes = { version = "0.11", optional = true }

[dev-dependencies]
tokio = { version = "0.2.11", features = [ "full" ] }