[package]
name = "holochain_wasm_test_utils"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "holochain_wasm_test_utils"
crate-type = [ "cdylib", "rlib" ]
path = "./src/lib.rs"

[dependencies]
fixt = { path = "../../fixt" }
holo_hash_ext = { path = "../../holo_hash_ext" }
holochain_types = { path = "../../types" }
holochain_zome_types = { path = "../../zome_types" }
rand = "0.7"
strum = "0.18.0"
strum_macros = "0.18.0"

[build-dependencies]
toml = "0.5"
walkdir = "2.3.1"
