[package]
name = "holochain_wasm_test_utils"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "holochain_wasm_test_utils"
crate-type = [ "cdylib", "rlib" ]
path = "./src/lib.rs"

[dependencies]
holochain_types = { path = "../../types" }
