version: 2.1

commands:
 build-docker:
  description: "Build and deploy a docker box"
  parameters:
   box:
    type: string
    default: "minimal"
  steps:
   - checkout
   - run: ./docker/login.sh
   - run:
      no_output_timeout: 45m
      command: ./docker/build.sh << parameters.box >> $CIRCLE_BRANCH
   - run:
      no_output_timeout: 30m
      command: ./docker/push.sh << parameters.box >> $CIRCLE_BRANCH

jobs:
  # must be called build
  build:
    docker:
     image: holochain/holochain-2020:circle.build.2020-04-15-dockerz
      # - image: holochain/holonix:latest.develop
     resource_class: xlarge
     steps:
       - checkout
       - run:
           command: nix-shell --run hc-merge-test

  docker-build-latest:
   resource_class: large
   machine: true
   steps:
    - build-docker:
       box: latest

  docker-build-circle-build:
   resource_class: large
   machine: true
   steps:
    - build-docker:
       box: circle.build

workflows:
 version: 2.1
 tests:
  jobs:
   - build
   - docker-build-latest
   - docker-build-circle-build
