version: 2.1

commands:
 build-docker:
  description: "Build and deploy a docker box"
  parameters:
   box:
    type: string
    default: "minimal"
  steps:
   - checkout
   - run: ./docker/login.sh
   - run:
      no_output_timeout: 45m
      command: ./docker/build.sh << parameters.box >> $CIRCLE_BRANCH
   - run:
      no_output_timeout: 30m
      command: ./docker/push.sh << parameters.box >> $CIRCLE_BRANCH

jobs:
  merge-test:
    docker:
     - image: holochain/holochain:circle.build.develop
       auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    resource_class: xlarge
    environment:
     NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - checkout
      - run:
          command: nix-shell --run hc-merge-test

  merge-test-mac:
   macos:
    xcode: "12.0.0"
   steps:
    - checkout
    - run:
       name: Test on mac
       no_output_timeout: 30m
       command: |
        sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
        . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
        nix-shell --run hc-merge-test

  docker-build-latest:
   resource_class: large
   machine: true
   steps:
    - build-docker:
       box: latest

  docker-build-circle-build:
   resource_class: large
   machine: true
   steps:
    - build-docker:
       box: circle.build

workflows:
 version: 2.1
 tests:
  jobs:
   - merge-test
   - merge-test-mac
 docker-builds:
  triggers:
   - schedule:
      cron: "0 0 * * *"
      filters:
       branches:
        only:
         - develop
         - master
  jobs:
   - docker-build-latest
   - docker-build-circle-build:
      requires:
       - docker-build-latest
