[package]
name = "test_wasm_debug"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
[workspace]

[lib]
name = "test_wasm_debug"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
# TODO: Investigate replacing "=x.x.x" version specifications with `--frozen` or `--locked`
wee_alloc = "=0.4.5"
holochain_wasmer_guest = "0.0.28"
test_wasm_common = { version = "=0.0.1", path = "../../wasm_common" }
holochain_serialized_bytes = "=0.0.39"
serde = "=1.0.104"
holochain_zome_types = { version = "=0.0.1", path = "../../../zome_types" }
lazy_static = "1.4.0"


[patch.crates-io]
# holochain_serialized_bytes = { version = "=0.0.39", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
# holochain_wasmer_common = { version = "=0.0.28", git = "https://github.com/holochain/holochain-wasmer.git", branch = "unpinned" }
# holochain_wasmer_guest = { version = "=0.0.28", git = "https://github.com/holochain/holochain-wasmer.git", branch = "unpinned" }
# holochain_wasmer_host = { version = "=0.0.28", git = "https://github.com/holochain/holochain-wasmer.git", branch = "unpinned" }
