[package]
name = "sx_wasm_test_utils"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "sx_wasm_test_utils"
crate-type = [ "cdylib", "rlib" ]
path = "./src/lib.rs"

[dependencies]
sx_types = { path = "../../crates/types" }

[patch.crates-io]
holochain_serialized_bytes = { version = "=0.0.36", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }
holochain_serialized_bytes_derive = { version = "=0.0.36", git = "https://github.com/holochain/holochain-serialization.git", branch = "unpinned" }