[package]
name = "holochain_p2p"
version = "0.0.1"
description = "holochain specific wrapper around more generic p2p module"
license = "0GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
keywords = ["holochain", "holo", "p2p", "dht", "networking"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
futures = "0.3"
ghost_actor = "0.1.0-alpha.9"
holo_hash = { version = "0.0.1", path = "../holo_hash" }
holochain_keystore = { version = "0.0.1", path = "../keystore" }
thiserror = "1.0.18"
tokio = { version = "0.2", features = ["full"] }
