[package]
name = "holochain_conductor_api"
version = "0.0.1"
description = "TODO minimize deps"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1"
base64 = "0.10.1"
byteorder = "1.3.4"
cfg-if = "0.1"
chrono = "0.4.6"
derivative = "2.1.1"
derive_more = "0.99.3"
directories = "2.0.2"
either = "1.5.0"
fallible-iterator = "0.2.0"
fixt = { version = "0.0.1", path = "../fixt" }
futures = "0.3.1"
ghost_actor = "0.3.0-alpha.1"
ring = "0.16"
holo_hash = { version = "0.0.1", path = "../holo_hash", features = ["full"] }
holochain_serialized_bytes = "=0.0.45"
holochain_wasmer_host = "=0.0.50"
hdk3 = { version = "0.0.1", path = "../hdk3" }
hdk3_derive = { version = "0.0.1", path = "../hdk3_derive" }
holochain_keystore = { version = "0.0.1", path = "../holochain_keystore" }
holochain_lmdb = { version = "0.0.1", path = "../holochain_lmdb" }
holochain_p2p = { version = "0.0.1", path = "../holochain_p2p" }
holochain_state = { version = "0.0.1", path = "../holochain_state" }
holochain_types = { version = "0.0.1", path = "../holochain_types" }
holochain_zome_types = { version = "0.0.1", path = "../holochain_zome_types" }
human-panic = "1.0.3"
lazy_static = "1.4.0"
mockall = "0.8"
must_future = "0.1.1"
nanoid = "0.3"
num_cpus = "1.8"
observability = "0.1"
parking_lot = "0.10"
predicates = "1.0.4"
rand = "0.7"
serde = { version = "1.0.104", features = [ "derive" ] }
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
serde_yaml = "0.8"
shrinkwraprs = "0.3.0"
structopt = "0.3.11"
strum = "0.18.0"
tempdir = "0.3.7"
thiserror = "1.0.22"
tokio = { version = "0.2.11", features = [ "full" ] }
tokio_safe_block_on = "0.1.2"
toml = "0.5.6"
tracing = "=0.1.21"
tracing-futures = "0.2.4"
url = "1.7.2"
url2 = "0.0.6"
url_serde = "0.2.0"
uuid = { version = "0.7", features = [ "serde", "v4" ] }
kitsune_p2p = { version = "0.0.1", path = "../kitsune_p2p/kitsune_p2p" }

# hdk3 = { path = "../hdk", optional = false }
matches = {version = "0.1.8", optional = false }
# crate::holochain_test_wasm_common = { version = "0.0.1", path = "originals/test_utils/wasm_common", optional = false  }
unwrap_to = { version = "0.1.0", optional = false }
itertools = { version = "0.9", optional = false }
lair_keystore_api = "=0.0.1-alpha.8"
lair_keystore_client = "=0.0.1-alpha.8"
strum_macros = "0.18.0"
rkv = "=0.10.4"
paste = "=1.0.3"
failure = "0.1.6"
subtle = "2"
holochain_wasmer_guest = "=0.0.50"
backtrace = "0.3.27"
derive_builder = "0.9.0"
regex = "1.1.2"
serde_bytes = "0.11"
rmp-serde = "0.14"
flate2 = "1.0.14"
serde_derive = "1.0.104"
net2 = "0.2"
tokio-tungstenite = { version = "0.10.1", features = [ "tls" ] }
tungstenite = "0.10"











[dev-dependencies]
anyhow = "1.0.26"
assert_cmd = "1.0.1"
criterion = "0.3"
maplit = "1"
pretty_assertions = "0.6.1"
serial_test = "0.4.0"
test-case = "1.0.0"
once_cell = "1.4.1"

# Dependencies for test_utils: keep in sync with above
# hdk3 = { path = "../hdk", optional = false }
matches = {version = "0.1.8", optional = false }
# crate::holochain_test_wasm_common = { version = "0.0.1", path = "originals/test_utils/wasm_common", optional = false  }
unwrap_to = { version = "0.1.0", optional = false }


# [[bench]]
# name = "bench"
# harness = false

# [lib]
# name = "holochain"
# path = "src/lib.rs"

# [[bin]]
# name = "holochain"
# path = "src/bin/holochain/main.rs"

[features]
default = ["slow_tests", "test_utils", "only_check_wasms", "fixturators"]
test_utils = [
    "holochain_state/test_utils",
    "holochain_types/test_utils",
    "holochain_zome_types/test_utils",
]
slow_tests = []
only_check_wasms = []
fixturators = []

# default = ["slow_tests", "test_utils", "only_check_wasms"]

# # Exposes additional functionality only needed for integration tests.
# # This feature should be turned off for production builds.
# test_utils = [
#   "hdk3",
#   "holochain_types/test_utils",
#   "matches",
#   "crate::holochain_test_wasm_common",
#   "unwrap_to"
# ]

# # Wasm ribosome tests take > 60 seconds - let's only run them in CI
# slow_tests = []

# # Includes the wasm build script, which we don't need when not building wasms
# # build_wasms = ['holochain_wasm_test_utils/build']
# only_check_wasms = ['holochain_wasm_test_utils/only_check']
