[package]
name = "holochain_conductor_api"
version = "0.0.1"
description = "Message types for Holochain admin and app interface protocols"
license = "CAL-1.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
kitsune_p2p = { version = "0.0.1", path = "../kitsune_p2p/kitsune_p2p" }
holo_hash = { version = "0.0.1", path = "../holo_hash", features = ["full"] }
holochain_serialized_bytes = "=0.0.45"
holochain_keystore = { version = "0.0.1", path = "../holochain_keystore" }
holochain_state = { version = "0.0.1", path = "../holochain_state" }
holochain_types = { version = "0.0.1", path = "../holochain_types" }
holochain_zome_types = { version = "0.0.1", path = "../holochain_zome_types" }
serde = { version = "1.0.104", features = [ "derive" ] }
serde_derive = "1.0.104"
tracing = "=0.1.21"
