[package]
name = "kitsune_p2p_transport_quic"
version = "0.0.1"
description = "QUIC transport module for kitsune-p2p"
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://github.com/holochain/holochain"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "p2p", "dht", "networking" ]
categories = [ "network-programming" ]
edition = "2018"

[dependencies]
futures = "0.3"
kitsune_p2p_types = { version = "0.0.1", path = "../types" }
lair_keystore_api = "0.0.1-alpha.5"
nanoid = "0.3"
quinn = "0.6.1"
rcgen = "0.8.5"
rustls = { version = "0.17", features = [ "dangerous_configuration" ] }
tokio = { version = "0.2", features = [ "full" ] }
webpki = "0.21.2"
