[package]
name = "test_wasm_xsalsa20_poly1305"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_xsalsa20_poly1305"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk3 = { path = "../../../../hdk" }
serde = "=1.0.104"
