[package]
name = "holochain_2020"
version = "0.0.1"
description = "Holochain, a framework for distributed applications"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1.24"
base64 = "0.10.1"
cfg-if = "0.1"
chrono = "0.4.6"
derive_more = "0.99.3"
directories = "2.0.2"
either = "1.5.0"
fallible-iterator = "0.2.0"
fixt = { version = "0.0.1", path = "../fixt" }
futures = "0.3.1"
ghost_actor = "0.2.0"
holo_hash = { version = "0.0.1", path = "../holo_hash" }
holo_hash_core = { version = "0.0.1", path = "../holo_hash_core" }
holochain_crypto = { version = "0.0.1", path = "../crypto" }
holochain_keystore = { version = "0.0.1", path = "../keystore" }
holochain_p2p = { version = "0.0.1", path = "../holochain_p2p" }
holochain_serialized_bytes = "=0.0.40"
holochain_state = { version = "0.0.1", path = "../state" }
holochain_types = { version = "0.0.1", path = "../types" }
holochain_wasm_test_utils = { version = "0.0.1", path = "../test_utils/wasm" }
# holochain_wasmer_host = "=0.0.33"
holochain_wasmer_host = { version = "=0.0.33", path = "../../../holochain-wasmer/crates/host" }
holochain_websocket = { version = "0.0.1", path = "../websocket" }
holochain_zome_types = { version = "0.0.1", path = "../zome_types" }
human-panic = "1.0.3"
lazy_static = "1.4.0"
legacy = { path = "../legacy", package = "holochain_2020_legacy" }
mockall = "0.7.0"
must_future = "0.1.1"
nanoid = "0.3"
num_cpus = "1.8"
parking_lot = "0.10.0"
predicates = "1.0.4"
rand = "0.7"
serde = { version = "1.0.104", features = [ "derive" ] }
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
shrinkwraprs = "0.3.0"
structopt = "0.3.11"
strum = "0.18.0"
tempdir = "0.3.7"
thiserror = "1.0.10"
tokio = { version = "0.2.11", features = [ "full" ] }
tokio_safe_block_on = "0.1.2"
toml = "0.5.6"
tracing = "=0.1.13"
tracing-futures = "0.2.3"
url = "1.7.2"
url2 = "0.0.5"
url_serde = "0.2.0"
uuid = { version = "0.7", features = [ "serde", "v4" ] }

[dev-dependencies]
anyhow = "1.0.26"
assert_cmd = "1.0.1"
matches = "0.1.8"
serial_test = "0.4.0"
test_wasm_common = { version = "0.0.1", path = "../test_utils/wasm_common" }
unwrap_to = "0.1.0"
pretty_assertions = "0.6.1"
criterion = "0.3"

[[bench]]
name = "bench"
harness = false

[lib]
name = "holochain_2020"
path = "src/lib.rs"

[[bin]]
name = "holochain-2020"
path = "src/bin/holochain/main.rs"

[features]
default = []

# wasm ribosome tests take > 60 seconds - let's only run them in CI
slow_tests = []
