[package]
name = "skunkworx_holochain"
version = "0.0.1"
description = "holochain skunkworx"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

[dependencies]
async-trait = "0.1.22"
futures = { version = "0.3.1", features = ["thread-pool"]}
sx_core = { path = "../core"}
parking_lot = "0.10.0"
tokio = { version = "0.2.11", features = ["macros", "rt-threaded", "rt-util", "sync"] }

[[bin]]
path = "src/main.rs"
name = "holochain-skunkworx"
