[package]
name = "holochain_zome_types"
version = "0.0.1"
description = "Holochain zome types"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain"
documentation = "https://github.com/Holo-host/holochain"
readme = "README.md"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
holo_hash = { path = "../holo_hash" }
holochain_serialized_bytes = "=0.0.42"
# TODO: remove and replace with HoloHash
multihash = "0.8.0"
# TODO: remove this once there is some less obtrusive source of randomness
nanoid = "0.3"
# TODO: remove and replace with HoloHash
rust-base58 = "0.0.4"
serde = { version = "1.0.104", features = [ "derive" ] }
serde_bytes = "0.11"
subtle = "2"
