[package]
name = "sx_types"
version = "0.0.1"
description = "holochain skunkworx common types"
license = "GPL-3.0-only"
homepage = "https://github.com/holochain/holochain-rust"
documentation = "https://github.com/holochain/holochain-rust"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "=0.10.1"
chrono = "=0.4.6"
hcid = "=0.0.6"
holochain_persistence_api = "=0.0.13"
holochain_json_api = "=0.0.17"
holochain_json_derive = "=0.0.17"
regex = "=1.1.2"
serde = "=1.0.89"
serde_derive = "=1.0.89"
serde_json = "=1.0.39"
lazy_static = "1.4.0"
multihash = "0.8.0"
snowflake = "1.3.0"

[patch.crates-io]
holochain_persistence_api = { version = "=0.0.13", git = "https://github.com/holochain/holochain-persistence.git", branch = "upgrade-to-real-futures" }
holochain_json_api = { version = "=0.0.17", git = "https://github.com/holochain/holochain-serialization.git", branch = "upgrade-to-real-futures" }
holochain_json_derive = { version = "=0.0.17", git = "https://github.com/holochain/holochain-serialization.git", branch = "upgrade-to-real-futures" }
