[package]
name = "holochain_types"
version = "0.0.1"
description = "Holochain common types"
license = "GPL-3.0-only"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.27"
base64 = "0.10.1"
chrono = "0.4.6"
flate2 = "1.0.14"
hcid = "0.0.6"
holo_hash = { version = "0.0.1", path = "../holo_hash" }
holo_hash_core = { version = "0.0.1", path = "../holo_hash_core" }
holochain_crypto = { version = "0.0.1", path = "../crypto" }
holochain_keystore = { version = "0.0.1", path = "../keystore" }
# holochain_locksmith = "0.0.43-alpha3"
lazy_static = "1.4.0"
regex = "1.1.2"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = { version = "1.0.51", features = ["preserve_order"] }
serde_bytes = "0.11"
snowflake = "1.3.0"
tokio = { version = "0.2", features = ["blocking"] }
tokio_safe_block_on = "0.1.1"
tracing = "=0.1.13"
tracing-core = "=0.1.10"
tracing-subscriber = "=0.2.3"
tracing-serde = "=0.1.1"
holochain_serialized_bytes = "=0.0.39"
holochain_types_derive = { version = "=0.0.1", path = "../types_derive" }
holochain_wasmer_common = "=0.0.30"
holochain_zome_types = { path = "../zome_types" }
futures = "0.3"
must_future = "0.1.1"

# for test_utils
anyhow = "1.0.26"
tempdir = "0.3.7"

# possibly dispensable
multihash = "0.8.0"
maplit = "1.0.2"
thiserror = "1.0.10"
derive_more = "0.99.3"
rust-base58 = "0.0.4"
shrinkwraprs = "0.3.0"

# dev deps?
rand = "0.7"
fixt = { path = "../fixt" }

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
matches = "0.1.8"
