[package]
name = "test_wasm_common"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_common"
crate-type = [ "cdylib", "rlib" ]
path = "src/common.rs"

[dependencies]
holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization", branch = "2020-06-06-serde-bytes" }
holochain_wasmer_common = { git = "https://github.com/holochain/holochain-wasmer", branch = "2020-06-05-criterion" }
serde = "=1.0.104"
serde_bytes = "0.11"
