[package]
name = "holo_hash"
version = "0.0.1"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"
categories = [ "cryptography" ]
keywords = [ "holochain", "holo", "hash", "blake", "blake2b" ]
description = "hashing helpers supporting dht sharding"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain"
documentation = "https://github.com/Holo-host/holochain"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.0"
blake2b_simd = "0.5.10"
derive_more = "0.99"
fixt = { version = "0.0.1", path = "../fixt" }
futures = "0.3.1"
holo_hash_core = { path = "../holo_hash_core", features = ["string-encoding"]}
holochain_serialized_bytes = "0.0.40"
must_future = "0.1.1"
rand = "0.7"
serde = { version = "1.0.104", features = [ "derive" ] }
thiserror = "1.0"

# may be able to remove with revisited SerializedBytes
rmp-serde = "0.14.3"

[dev-dependencies]
tokio = { version = "0.2", features = [ "full" ] }
