[package]
name = "holo_hash_core"
version = "0.0.1"
authors = ["Michael Dougherty <maackle.d@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = {version = "0.12.0", optional = true}
blake2b_simd = {version = "0.5.10", optional = true}
futures = "0.3.1"
holochain_serialized_bytes = "0.0.40"
must_future = "0.1.1"
serde = "1"
serde_bytes = "0.11"

# may be able to remove with custom SerializedBytes impl
rmp-serde = "0.14.3"

[features]
default = []
string-encoding = ["base64", "blake2b_simd"]
