[package]
name = "holo_hash_core"
version = "0.0.1"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "hash", "blake", "blake2b" ]
categories = [ "cryptography" ]
edition = "2018"
description = "hashing helpers supporting dht sharding"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain"
documentation = "https://github.com/Holo-host/holochain"

[dependencies]
base64 = {version = "0.12.0", optional = true}
blake2b_simd = {version = "0.5.10", optional = true}
holochain_serialized_bytes = "0.0.40"
serde = "1"
serde_bytes = "0.11"

# may be able to remove with custom SerializedBytes impl
rmp-serde = "0.14.3"

[features]
default = []
string-encoding = ["base64", "blake2b_simd"]
