[package]
name = "holo_hash_core"
version = "0.0.1"
description = "hashing helpers supporting dht sharding"
license = "CAL-1.0"
homepage = "https://github.com/Holo-host/holochain-2020"
documentation = "https://github.com/Holo-host/holochain-2020"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "hash", "blake", "blake2b" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
holochain_serialized_bytes = "=0.0.40"
serde = { version = "1.0.104", features = [ "derive" ] }
serde_bytes = "0.11"
