[workspace]
members = [
    "agent_info",
    "anchor",
    "bench",
    "commit_entry",
    "crd",
    "crud",
    "debug",
    "entry_defs",
    "entry_hash",
    "foo",
    "hash_path",
    "imports",
    "init_fail",
    "init_pass",
    "link",
    "migrate_agent_fail",
    "migrate_agent_pass",
    "post_commit_fail",
    "post_commit_success",
    "random_bytes",
    "ser_regression",
    "sys_time",
    "validate",
    "validate_invalid",
    "validate_link",
    "validate_link_add_invalid",
    "validate_link_add_valid",
    "validate_valid",
    "validation_package_fail",
    "validation_package_success",
    "whoami",
    "zome_info",
]

[profile.release]
opt-level = "z"


[patch.crates-io]
# holochain_serialized_bytes = { path = "/home/michael/Holo/holochain-serialization/crates/holochain_serialized_bytes" }
holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization.git", branch = "reading-rainbow" }
