name: Is Ready To Merge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  can_merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - uses: docker://holochain/holochain-rust:circle.build.develop
    - name: Merge Test
      run: nix-shell --run 'hc-merge-test'
